name: example_docs
channels:
  - conda-forge
  - defaults
dependencies:
   - python=3.10
   - numpy
   # These are needed for the docs themselves
   - ghp-import
   - jupytext
   - numpydoc
   - requests
   - sphinx
   - sphinx-markdown-tables
   - ipython
   - nbconvert
   - nbformat
   - ipykernel
   - pandoc
   - pip
   - recommonmark
   - pip:
     - docrep<=0.2.7
     - furo
     - nbsphinx
     - jupyter_client
     - myst-nb
     - sphinx_pangeo_theme
     - sphinx-copybutton
     - sphinxcontrib-srclinks
